[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
name = "voice"
version = "0.1.0"

[dependencies]
petgraph = "0.4.1"
rustc-serialize = "0.3.19"
time = "0.1.35"
toml = "0.2.1"

[dependencies.clippy]
optional = true
version = "~0.0.95"
